### ISSUE TITLE
generate .d.ts file

### ISSUE THREAD

**Issue by deblockt** [urish/angular2-material-build#5]
Hello,

Have you generate the .d.ts file for TypeScript angular 2?
I try install try to install with tsd, but the .d.ts matches the angular 1 material. Is the same file?

Thank's

**Comment by urish** [comment]
Nope, I haven't...

**Comment by deblockt** [comment]
Ok,

And how can I use :

``` typescript
import {MdCheckbox} from 'angular2_material/material';
```

need I to rebuild material angular module?

Thanks
